### ISSUE TITLE
Display Date Label as group in axes - ng2 charts

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#1003]
Need to display labels date in the x axes in the interval . Data should remain same only date interval shoould be displayed as per the snapshot.
![snapshot](https://user-images.githubusercontent.com/32042376/41765414-a026d636-7621-11e8-96ce-3181a3560e68.jpg)

For simple numbers on y axes able to achieve this using "ticks"

            max: 5000,
            min: 0,
            stepSize:4000
But in case of date not sure the property which is to be used. Attached the code snippet stackblitz url https://stackblitz.com/edit/ng2-chart-example-5xxqc9?file=app/app.component.ts

**Comment by Joklogh** [comment]
Hi @manhar-developer. If you want to change labels on x-axis, you want to add in options of the graph, in xAxes, in ticks, function called callback which will run on every label(called ticks) on the x-axis. This method must return new text which will be displayed in individual tick.
In order to change ticks to dates, I started in `ngOnInit` hook by filtering chartLabels and making new array of the months present in labels.
My `ngOnInit` hook : 
`let currentMonth = this.ChartLabels[0].split(' ')[1] + ' ' +this.ChartLabels[0].split(' ')[3];
    this.monthsLabel[0] = currentMonth;
    for(let i = 1; i < this.ChartLabels.length; i++){
      let month = this.ChartLabels[i].split(' ')[1] + ' ' +this.ChartLabels[i].split(' ')[3];
      if(currentMonth != month){
        this.monthsLabel[i] = month;
        currentMonth = month;
      }
    }`
Then in `callback` of the `ticks` I simply return month if it is in the `monthsLabel` object by checking index of ticks. So my final code in `callback` looks like this : 
`callback : (label, index) => {
                  return this.monthsLabel[index] ? this.monthsLabel[index] : '';
                }
` 
If you don't understand feel free to ask questions, I hope this is the solution you want :)

**Comment by paviad** [comment]
I would process the labels array and make a new array with the proper labels, for example:

```typescript
const originalDates = [
  new Date(2018, 1, 1),
  new Date(2018, 1, 2),
  new Date(2018, 1, 3),
  new Date(2018, 1, 4),
  new Date(2018, 1, 5),
  new Date(2018, 2, 1),
  new Date(2018, 2, 2),
  new Date(2018, 2, 3),
  new Date(2018, 2, 4),
  new Date(2018, 2, 5),
  new Date(2018, 2, 6),
  new Date(2018, 3, 1),
  new Date(2018, 3, 2),
  new Date(2018, 3, 3),
  new Date(2018, 3, 4),
  new Date(2018, 3, 5),
  new Date(2018, 3, 6),
];

const filteredDates = originalDates.map((v, i) => {
  const getKey = (date: Date) => `${date.getMonth() + 1}/${date.getFullYear()}`;
  const keyOfV = getKey(v);
  if (i === 0) {
    return keyOfV;
  } else if (keyOfV === getKey(originalDates[i - 1])) {
    return '';
  } else {
    return keyOfV;
  }
});

console.log('original dates', originalDates);
console.log('filtered dates', filteredDates);
```

And this would be the output:

```
original dates [ 2018-01-31T22:00:00.000Z,
  2018-02-01T22:00:00.000Z,
  2018-02-02T22:00:00.000Z,
  2018-02-03T22:00:00.000Z,
  2018-02-04T22:00:00.000Z,
  2018-02-28T22:00:00.000Z,
  2018-03-01T22:00:00.000Z,
  2018-03-02T22:00:00.000Z,
  2018-03-03T22:00:00.000Z,
  2018-03-04T22:00:00.000Z,
  2018-03-05T22:00:00.000Z,
  2018-03-31T21:00:00.000Z,
  2018-04-01T21:00:00.000Z,
  2018-04-02T21:00:00.000Z,
  2018-04-03T21:00:00.000Z,
  2018-04-04T21:00:00.000Z,
  2018-04-05T21:00:00.000Z ]
filtered dates [ '2/2018',
  '',
  '',
  '',
  '',
  '3/2018',
  '',
  '',
  '',
  '',
  '',
  '4/2018',
  '',
  '',
  '',
  '',
  '' ]
```
