### ISSUE TITLE
Dynamic values getting updated in dataset but not redrawing chart

### ISSUE THREAD

**Issue by rohanc202** [valor-software/ng2-charts#1187]
I am using chart.js with ng2-chart where i have to update dataset on button click.

This is how i am reassigning the dataset and labels ;

---------------------------------------
    this.mfData.getMFData('http://www.mocky.io/v2/5ddcf6143400000f55eae607').subscribe(res => {
      res.data.Prices.forEach(element => {
        this.fundData.push(parseInt(element.v));
        this.fundLabel.push(element.d);
      });
      this.lineChartData = [{
          data: this.fundData,
          label: 'Series A',
          lineTension: 0,
          pointRadius: [4, 4, 4, 4],
          borderWidth: 6,
          pointHoverBorderWidth: 8
        }];
      this.lineChartLabels = this.fundLabel;
      this.testChart.chart.update();
    });
-----------------------------------------------------------------
HTML Code :

        <canvas #testChart='base-chart' baseChart *ngIf="showChart"
          [datasets]="lineChartData"
          [labels]="lineChartLabels"
          [options]="lineChartOptions"
          [colors]="lineChartColors"
          [legend]="lineChartLegend"
          [chartType]="lineChartType">
        </canvas>

------------------------------------

Value is being assigned to the 'lineChartData' but the graph is not updated, it vanishes after this method call.

**Comment by knight37x** [comment]
Has anyone found a solution, yet?

**Comment by dudewad** [comment]
Without seeing more code this appears to me to actually be an Angular change detection issue. You're subscribed to an observable, but you're also calling update manually.
I would bet that if you updated this to use the change detector ref to detect changes, your input binding would trigger a change detection cycle in the actual chart component - calling update without change detection means that it's updating against the old value since angular hasn't updated the component with the new data yet.

**Comment by santam85** [comment]
Change detection will not detect deeply nested property changes, call the directive instance update method to force a refresh.
