### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Maistho** [valor-software/ng2-charts#1196]
Hello, could someone release the current master as a new version on npm? v2.3.0 still imports all of lodash and is making the bundle size larger than necessary.

Thanks for all your work! :clap:

**Comment by cwoolum** [comment]
I'm beginning to think this project has been abandoned. Nobody is responding to issues and it's been 3 months since any code changes.

**Comment by tobiasbueschel** [comment]
Agreed, would also love to see a new release so that we can reduce our bundle size!

However, the project is currently looking for new maintainers from what I can see on the readme:
![image](https://user-images.githubusercontent.com/13087421/75425712-364d2c00-597e-11ea-9f44-602bfa9304b7.png)

I'm not sure if anyone has been found yet?

**Comment by paviad** [comment]
We got an energetic new maintainer @santam85 :)
