### ISSUE TITLE
Error after updating the vesion 2.3.2 to 2.4.0

### ISSUE THREAD

**Issue by atuljain707** [valor-software/ng2-charts#1255]
ERROR NullInjectorError: StaticInjectorError(AppModule)[BaseChartDirective -> ThemeService]: 
  StaticInjectorError(Platform: core)[BaseChartDirective -> ThemeService]: 
    NullInjectorError: No provider for ThemeService!

**Comment by ziqbalbh** [comment]
I am having same issue - angular version is 8, while it works with 9

**Comment by VinodKumar-b** [comment]
I am also having the same issue. is there any solution without updating the angular version. I am using Angular 8.

**Comment by feralva** [comment]
I have the same problem

> Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[BaseChartDirective -> ThemeService]: 
  StaticInjectorError(Platform: core)[BaseChartDirective -> ThemeService]: 
    NullInjectorError: No provider for ThemeService!
NullInjectorError: StaticInjectorError(AppModule)[BaseChartDirective -> ThemeService]: 
  StaticInjectorError(Platform: core)[BaseChartDirective -> ThemeService]: 
    NullInjectorError: No provider for ThemeService!
    at NullInjector.get (http://localhost:8100/vendor.js:39072:27)
    at resolveToken (http://localhost:8100/vendor.js:53990:24)
    at tryResolveToken (http://localhost:8100/vendor.js:53916:16)
    at StaticInjector.get (http://localhost:8100/vendor.js:53766:20)
    at resolveToken (http://localhost:8100/vendor.js:53990:24)
    at tryResolveToken (http://localhost:8100/vendor.js:53916:16)
    at StaticInjector.get (http://localhost:8100/vendor.js:53766:20)
    at resolveNgModuleDep (http://localhost:8100/vendor.js:64953:29)
    at NgModuleRef_.get (http://localhost:8100/vendor.js:66019:16)
    at resolveNgModuleDep (http://localhost:8100/vendor.js:64953:29)

**Comment by ziqbalbh** [comment]
add ThemeService in provider section in app.module.ts, this will resolve this error.

**Comment by parthi0216** [comment]
> add ThemeService in provider section in app.module.ts, this will resolve this error.

Resolved. Thank you

**Comment by navinbcs** [comment]
> 
> 
> add ThemeService in provider section in app.module.ts, this will resolve this error.

It works

**Comment by satinder99** [comment]
> add ThemeService in provider section in app.module.ts, this will resolve this error.

Thanks. It works

**Comment by Blqck666** [comment]
> add ThemeService in provider section in app.module.ts, this will resolve this error.

what exactly should i add ?

**Comment by satinder99** [comment]
> > add ThemeService in provider section in app.module.ts, this will resolve this error.
> 
> what exactly should i add ?

You have to add ThemeService in providers array in your module file. For example : 

/*app.module.ts*/
-------
imports : [
     --------],
providers : [ThemeService]
---------
---------
/*end of module file*/

**Comment by sharadchandra** [comment]
HI,
I have included Provide as mentioned above, but still getting below error:

ERROR TypeError: Cannot read property 'getColorschemesOptions' of undefined
    at BaseChartDirective.getChartConfiguration (ng2-charts.js:694)
    at BaseChartDirective.getChartBuilder (ng2-charts.js:711)
    at BaseChartDirective.refresh (ng2-charts.js:886)
    at BaseChartDirective.ngOnInit (ng2-charts.js:328)
    at checkAndUpdateDirectiveInline (core.js:31910)
    at checkAndUpdateNodeInline (core.js:44367)
    at checkAndUpdateNode (core.js:44306)
    at debugCheckAndUpdateNode (core.js:45328)
    at debugCheckDirectivesFn (core.js:45271)

I have injected ThemeService in component.ts file as well

**Comment by navinbcs** [comment]
'getColorschemesOptions'  this is not defined you can use hard coded Sent from Mail for Windows 10 From: sharadchandraSent: Friday, September 25, 2020 10:26 AMTo: valor-software/ng2-chartsCc: navinbcs; CommentSubject: Re: [valor-software/ng2-charts] Error after updating the vesion 2.3.2 to 2.4.0 (#1255) HI,I have included Provide as mentioned above, but still getting below error:ERROR TypeError: Cannot read property 'getColorschemesOptions' of undefinedat BaseChartDirective.getChartConfiguration (ng2-charts.js:694)at BaseChartDirective.getChartBuilder (ng2-charts.js:711)at BaseChartDirective.refresh (ng2-charts.js:886)at BaseChartDirective.ngOnInit (ng2-charts.js:328)at checkAndUpdateDirectiveInline (core.js:31910)at checkAndUpdateNodeInline (core.js:44367)at checkAndUpdateNode (core.js:44306)at debugCheckAndUpdateNode (core.js:45328)at debugCheckDirectivesFn (core.js:45271)I have injected ThemeService in component.ts file as well—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by srmmahe** [comment]
providers : [ThemeService]  add in appmodule.ts the same error i resloved

**Comment by assmabenmussa** [comment]
@ziqbalbh thank you! this works :)
