### ISSUE TITLE
hoverBackgroundColor uses default colors when it should be calculated based on backgroundColor

### ISSUE THREAD

**Issue by mihilion** [valor-software/ng2-charts#1493]
If `hoverBackgroundColor` is not set, it should be calculated based on provided `backgroundColor` - chart.js code:
```
this.hoverBackgroundColor = (ctx, options) => getHoverColor(options.backgroundColor);
```

With ng2-charts it is not - it uses the DEFAULT `backgroundColor` to calculate `hoverBackgroundColor` instead of the one provided. Interesting thing is that with ng2-charts installed, this problem occurs no matter if you create your chart using ng2-charts, or pure javascript:
https://stackblitz.com/edit/labs-ng2-charts-3-zvoc3u?file=src/app/app.component.html

The moment you uninstall ng2-charts, pure javascript version starts working as it should:
https://stackblitz.com/edit/labs-ng2-charts-3-zkpcyx?file=package.json

The same thing happens to `hoverBorderColor` - with ng2-charts it is also resolved to default color, while in pure chart.js it is resolved based on provided `borderColor` - chart.js code:
```
this.hoverBorderColor = (ctx, options) => getHoverColor(options.borderColor);
```

I think the problem is related to this topic from 8 months ago: https://github.com/valor-software/ng2-charts/issues/1375 - @Santam85 said something about ng2-charts overriding the original defaults, which I believe is the source of the problem which I have encountered. @chinahnzl has attached a screenshot with gray hover color, now the hover color is not gray but it is default, so I guess someone has looked into it and now ng2-charts can do hovering properly on default colors - unfortunately for default colors only. Any chance I will be able to use your library soon without having to manually define `hoverBorderColor` and `hoverBackgroundColor` for every color I use?

**Comment by santam85** [comment]
@mihilion you can override the global defaults with ng2-charts too, passing it to the module with forRoot. The library does this at the moment: https://github.com/valor-software/ng2-charts/blob/master/projects/ng2-charts/src/lib/get-colors.ts

I am not sure I fully understand how to correct the issue, do you think you can try opening a PR to address it?

**Comment by santam85** [comment]
The idea of the code there is to generate a visually pleasing palette of colors for when multiple datasets are used. To my knowledge Chart.js does not do that internally, and expects all colors to be defined at dataset level, otherwise the same is going to be used for everything.

We might have missed some properties where the default is not inheriting properly, but I think that's something that can be fixed by adding a few more scripted properties in the file linked before. The current workaround would be defining the color on the dataset directly.

If that behaviour is bothering you and would like to disable it, I think I can easily add an option to the library config to prevent colors generation altogether, and default it to false. That way it's not a breaking change for existing users that enjoy the feature, and you can easily achieve what you are after?

**Comment by mihilion** [comment]
Yes, adding an option to the library config to use defaults from chart.js would be great, I would appreciate that.
