### ISSUE TITLE
How to display data values in Bar chart and Line Chart

### ISSUE THREAD

**Issue by lekova** [valor-software/ng2-charts#315]
I am trying the line chart and bar chart from the ng2-charts demo with the hardcoded values and want to be able to show the number values in the chart.
Like so:

![bkp0r](https://cloud.githubusercontent.com/assets/12982223/16926649/a28e23b6-4cf7-11e6-8403-aa434cecb6cc.png)

I tried to change the options with no success:

``` typescript
public lineChartOptions: any = {
      scaleShowValues: true, 
      scaleValuePaddingX: 10,
      scaleValuePaddingY: 10,
};
```

**Comment by Hongbo-Miao** [comment]
https://github.com/chartjs/Chart.js/issues/2477 might help.

**Comment by BenDevelopment** [comment]
@lekova Did youmanage to display the values? I'm facing the same problem.

**Comment by alexyangjie** [comment]
I am having the same issue. It seems the _meta object is missing in the dataset object. Without it I can't get the x and y coordinates of the data points to fill the values.

**Comment by lekova** [comment]
@BenDevelopment I've not. The project i was working on got frozen, I'm planing on doing something similar tho, so if someone figured it out, i would appreciatee it!

**Comment by kajalbh99** [comment]
[https://github.com/valor-software/ng2-charts/issues/662](url)

**Comment by paviad** [comment]
The `chartjs-plugin-datalabels` plugin handles displaying any information on top of bars/pie slices etc. Please see the [demo app](https://valor-software.com/ng2-charts) for examples (under bar and pie charts).

**Note** The datalabels plugin registers itself automatically upon load, so that it applies to all charts. In order to only apply it to selected charts, it needs to be unregistered globally, and then included in the inline plugins array for each chart. This is all demonstrated in the demo app.

**Comment by mogo-edenpark** [comment]
> I am trying the line chart and bar chart from the ng2-charts demo with the hardcoded values and want to be able to show the number values in the chart.
> Like so:
> 
> ![bkp0r](https://cloud.githubusercontent.com/assets/12982223/16926649/a28e23b6-4cf7-11e6-8403-aa434cecb6cc.png)
> 
> I tried to change the options with no success:
> 
> ```ts
> public lineChartOptions: any = {
>       scaleShowValues: true, 
>       scaleValuePaddingX: 10,
>       scaleValuePaddingY: 10,
> };
> ```

can you show me how you did show the labels on the line chart? any exmaples
