### ISSUE TITLE
Disabling legends on radar 

### ISSUE THREAD

**Issue by NicolasMrc** [valor-software/ng2-charts#338]
When drawing a radar chart, simply disable legends breaks startingPoint and endingPoint of the chart.

Options I apply to my chart : 

`chartOptions = {
            legend: { display: false },
        };`

My radar chart when using this option :  

![capture d ecran 2016-07-30 a 20 51 38](https://cloud.githubusercontent.com/assets/10900390/17272480/8394a8e6-5697-11e6-8413-0de779955099.png)

My radar chart when simply removing then legend line from options : 

![capture d ecran 2016-07-30 a 20 51 54](https://cloud.githubusercontent.com/assets/10900390/17272492/b7a06f62-5697-11e6-8874-41e4b5df54a3.png)

**Comment by Hongbo-Miao** [comment]
Hi @Nyckoo, ng2-charts is just a port & modification of Chart.js component for Angular 2. The issue may be related with Chart.js instead of ng2-charts.
To confirm, please try to reproduce using a [pure Chart.js starting template](https://jsfiddle.net/Hongbo_Miao/mvct2uwo/)

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
[ng2-charts starting template](http://plnkr.co/edit/7fGsiuRjcF0M0Ffeoml2?p=preview)

Thanks

**Comment by SergeyKuryatnick** [comment]
@NicolasMrc 
is this issue still actual?

**Comment by reignydeyz** [comment]
I've encountered the same issue too. Fortunately, I've found the solution. Thanks to this...
https://stackoverflow.com/questions/36955217/how-to-disable-the-legends-in-chart-js

TS:
```js
public memberChartOptions: any = {
        responsive: true,
        legend: {
            display: false,
            labels: {
                display: false
            }
        }
    };
```
HTML:
```html
<canvas baseChart
       [data]="memberStats.values"
       [labels]="memberStats.labels"
       [options]="memberChartOptions"
       [chartType]="memberChartType"></canvas>
```
