### ISSUE TITLE
Use JSON data to display charts

### ISSUE THREAD

**Issue by rohitbobade** [valor-software/ng2-charts#339]
Hi, Can you please help me on how to use JSON data to display charts

Thanks

**Comment by brandonreid** [comment]
@rohitbobade You'll need to manipulate your JSON data so that it's structured the way the chart needs it. You'll probably do this by running a for loop over it. Your question is way to vague for me or anyone to provide any more help than that.

**Comment by Hongbo-Miao** [comment]
Hi @rohitbobade Please considering using Stack Overflow for questions using [`angular2`](http://stackoverflow.com/questions/tagged/angular2) tag, and also [Angular 2 Gitter](https://gitter.im/angular/angular)
You will get more quick response from the Angular 2 community.

Since this is not an issue of ng2-charts, I will close it.
