### ISSUE TITLE
Doughnut chart legend display

### ISSUE THREAD

**Issue by raajeshem80** [valor-software/ng2-charts#374]
Hi,

How to place the inner-legend on doughnut chart and and to display the counts on titles?

**Comment by Hongbo-Miao** [comment]
Welcome to GitHub, please consider using

- Stack Overflow http://stackoverflow.com/questions/tagged/ng2-charts
- Gitter https://gitter.im/valor-software/ng2-bootstrap
- Slack https://ng2.slack.com

for **questions**. Thanks

ng2-charts is just a port & modification of Chart.js component for Angular 2

Since this is not a **issue** of ng2-charts, I will close it now.
