### ISSUE TITLE
ng2 Prefix

### ISSUE THREAD

**Issue by chrisparton1991** [valor-software/ng2-charts#702]
Hi there,
This is just a question, not an issue.

Now that Angular 4 is out, the `ng2-` prefix isn't really valid any more:
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/toddmotto">@toddmotto</a> <a href="https://twitter.com/manekinekko">@manekinekko</a> <a href="https://twitter.com/jdfwarrior">@jdfwarrior</a> <a href="https://twitter.com/schwarty">@schwarty</a> but please don&#39;t call projects ng2- or angular2-, etc.</p>&mdash; Igor Minar (@IgorMinar) <a href="https://twitter.com/IgorMinar/status/807564558986514432">December 10, 2016</a></blockquote>

This is an interesting quandary that's going to affect lots of libraries. Do you see a rename being feasible?

Looks like the prefix `ngx-` is an option being considered by others:
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">It looks like ng2-bootstrap is getting renamed to ngx-bootstrap. Next on my wishlist is merging the two so we have one amazing bootstrap lib <a href="https://t.co/bV4s9yierv">https://t.co/bV4s9yierv</a></p>&mdash; Igor Minar (@IgorMinar) <a href="https://twitter.com/IgorMinar/status/843483148558069762">March 19, 2017</a></blockquote>

**Edit:** Looks like `ngx-charts` is taken on NPM. `ng-charts` appears to be free though. I don't think the Angular folks like third party libraries using the `ng-` prefix though, in case of collisions...

**Comment by zbagley** [comment]
This naming convention was really not thought through well by the Angular team. Angularjs vs. Angular 2 has completely different naming conventions, and serious core changes (especially with observables). As far as I've seen Angular 4 would have been better named Angular 2.1.0, or similar, since this seems to be a minor upgrade (and they're already working on Angular 5, which will be a similar small patch, backwards compat, update).

It's already a pain to have to search Angular 2 over Angularjs, and with all these new numbers coming for angular it's just going to make debugging all that much harder.

Anyways, good point. A new name would be nice to alert people that this isn't a dead repo.

**Comment by chrisparton1991** [comment]
@zbagley I certainly agree with you about the naming being poorly handled. I have a feeling they didn't know they'd be committing to regular major version changes when they initially released Angular 2, otherwise you'd think they would have given more guidance around recommended naming conventions.

I think the `ng2-` prefix will be an anachronism that the community will get used to.

Let's just hope that people don't start releasing `ng4-` libraries :)
