### ISSUE TITLE
chart click doesn't return useful information

### ISSUE THREAD

**Issue by fctucker** [valor-software/ng2-charts#878]
Feature request: the call back for `chartClick` doesn't return useful information.  It simply returns a generic mouse click event.  It would be nice to handle legend clicks and filter events and pass chart specific information to the callback handler.

Thanks

**Comment by nukec** [comment]
would be cool if we could get data set info for clicked item so we could do another query into database to replace chart only for that info for example :)

**Comment by esoyke** [comment]
This can be done by defining your event handler with Chart.js' options instead of ng2-charts chartClick event in the component. Add a second argument to this handler and it will return a ChartElement object. The ChartElement is a one element array which contains an _index value, which corresponding to your original data array. :)

`<canvas baseChart
                                [data]="myData"
                                [labels]="myLabels" 
                                [chartType]="doughnutChartType"
                                [options]="chartOptions">
    </canvas>`

`  public chartOptions:any = {       
        onClick: this.graphClickEvent
    } 
    
    graphClickEvent(event, array){
        console.log('clicked on data index ',array[0]._index)
    }`

**Comment by leonardopaiva** [comment]
for anyone trying to take the data, remember to check for active[0]._index the _index is the index of the corresponding array value (lineChartData).

**Comment by leonardopaiva** [comment]
but i still miss an easy way to take the data

**Comment by paviad** [comment]
@leonardopaiva has the right idea, it might not be easy, but that's how `chart.js` implemented it.

**Comment by Chanmta** [comment]
thank you  esoyke your comment very helpful for me
