### ISSUE TITLE
ng2-charts Server side rendering ??

### ISSUE THREAD

**Issue by azzaGarsaa** [valor-software/ng2-charts#991]
Does ng2-charts support Server side rendering angular 5 (Angular Universal)

**Comment by luisdavis** [comment]
im getting this error on server side rendering  ```Prerendering failed because of error: ReferenceError: Chart is not defined at D:\home\site\wwwroot\ClientApp\node_modules\ng2-charts\bundles\ng2-charts.umd.js:1062:19```

**Comment by paviad** [comment]
Can you provide steps on how to reproduce this?

**Comment by FreiB** [comment]
I'm having the same SSR error as luisdavis. you can reproduce it simply by importing ChartsModule in any Angular Universal enabled project.
The error is caused by these lines in [monkey-patch-chart-js-legend.ts](https://github.com/valor-software/ng2-charts/blob/development/projects/ng2-charts/src/lib/monkey-patch-chart-js-legend.ts):

```
const helpers = Chart.helpers;
const defaults = Chart.defaults;
const valueOrDefault = helpers.valueOrDefault;
```

Downgrading to 2.0.3 will fix the error.

**Comment by tuanuvt001** [comment]
@FreiB 
Im get Chart is not defined too. 
Downgrading to 2.0.3 or 2.1.0 not work

**Comment by P0wersl4ve** [comment]
@tuanuvt001 @azzaGarsaa  these are the versions I am currently using in my project with angular 7/ Universal take a look and let me know if they worked for you! =)
    "chart.js": "^2.7.3",
    "ng2-charts": "^1.6.0",

**Comment by tuanuvt001** [comment]
@P0wersl4ve thanks. I found a solution 
add `global['Chart'] = Chart; ` in prerender.ts
