### ISSUE TITLE
can't show  on single graph with *ngFor

### ISSUE THREAD

**Issue by arsewizz** [valor-software/ng2-charts#994]
I have a problem too, when I use a loop I have two results instead of a single graph
`<div *ngFor="let datas of data">

      <div style="display: block">
          <canvas baseChart
                      [data]="[datas.montant]"
                      [labels]="[datas.motif]"
                      [chartType]="doughnutChartType"
                      (chartHover)="chartHovered(datas)"
                      (chartClick)="chartClicked(datas)"></canvas>
        </div>    
  </div>`

**Comment by Joklogh** [comment]
Hi @arsewizz 
If you want to use multiple data in single graph, you must bind to `datasets` instead of `data`.
Dataset is array consisting of objects. Each object has data array, where you put your data for first label, and actual label which is string. Both are required.
Example of dataset : 
`let dataset = [
  {
     data : number[] <--values to show,
     label : string <-- label to show in legend
  },
 //second dataset
 {
   data : number[] <--values to show,
   label : string <-- label to show in legend
 }
]`
If you don't undestand or need specific example feel free to ask.
